name: Lint

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: use Node.js 14.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1
          registry-url: https://npm.pkg.github.com
          scope: winstrike
      - name: Install dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      - name: Lint
        run: yarn lint
